function pbs_run_b(array_size, array_id)
experiment_name = strcat('MCS_dataset', '03_ov');

output_dir=fullfile('/home/hxm_stu/WORK1/hcq/MCS/Result/', experiment_name);
input_dir='/home/hxm_stu/WORK1/hcq/Data/CLAUS/';
source_code_path = '/home/hxm_stu/WORK1/hcq/MCS_v0/';

addpath(genpath(source_code_path));

% Global tropical
% 198501 ~ 200812, 24*12 = 288
% 30N~30S
time_list = task_assign(1985, 1, 2008, 12, array_size, array_id);

mcsDetect(input_dir, output_dir,...
    'is_rewrite', false,...
    'x1', 180, 'x2', 360,...
    'y1', 1, 'y2', 1080,...
    'age_threshold', 1,...
    'tracking_method', 'overlapping',...
    'shield_temperature_threshold', 233,...
    'shield_area_threshold', 5000,...
    'interest_date_begin', time_list.interest_begin_date,...
    'interest_date_end', time_list.interest_end_date,...
    'record_date_begin', time_list.record_begin_date,...
    'record_date_end', time_list.record_end_date)

